/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ics.upjs.sk.paz1c.skladnik.gui;

import Factory.ObjectFactory;
import dao.MaterialDao;
import dao.PohybMaterialuDao;
import dao.PouzivatelDao;
import dao.PrijemkaDao;
import dao.VydajkaDao;
import ics.upjs.sk.paz1c.skladnik.entity.Pouzivatel;
import ics.upjs.sk.paz1c.skladnik.entity.Prijemka;
import ics.upjs.sk.paz1c.skladnik.entity.Vydajka;
import ics.upjs.sk.paz1c.skladnik.entity.Material;
import ics.upjs.sk.paz1c.skladnik.entity.PohybMaterialu;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Marcel
 */
public class MainScreen extends javax.swing.JFrame {

    PrijemkaDao prijemkaDao = ObjectFactory.INSTANCE.getPrijemkadDao();
    PouzivatelDao pouzivatelDao =ObjectFactory.INSTANCE.getPouzivatelDao();
    VydajkaDao vydajkaDao = ObjectFactory.INSTANCE.getVydajkaDao();
    MaterialDao materialDao = ObjectFactory.INSTANCE.getMaterialDao();
    PohybMaterialuDao pohybMaterialuDao=ObjectFactory.INSTANCE.getPohybMaterialuDao();
    DefaultTableModel tableModel; 
    String model="";
    

    
    public MainScreen() {
        initComponents(); 
        tableModel = (DefaultTableModel) mainTable.getModel();  
        //dokoncit pre inicializaciu aby sa zobrazilo nieco v tabulke
        //naplnTabulkuPrijmi(tableModel, prijemkaDao.getAllByUzivatelId(pouzivatelDao.dajPouzivateloveId(uzivatelLable.getText())));
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ukazPrijmiButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        ukazMaterialButton = new javax.swing.JButton();
        ukazVydajebutton = new javax.swing.JButton();
        vytvorVydajkuButton = new javax.swing.JButton();
        jPridajKartuMaterialuButton5 = new javax.swing.JButton();
        vytvorPrijemkuButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        uzivatelLable = new javax.swing.JLabel();
        jVypisyButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        deleteSelectedButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        ukazPrijmiButton.setBackground(new java.awt.Color(0, 102, 0));
        ukazPrijmiButton.setText("Prijmy");
        ukazPrijmiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ukazPrijmiButtonActionPerformed(evt);
            }
        });

        mainTable.setBackground(new java.awt.Color(0, 204, 0));
        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "cena", "id_pouzivatela", "datum", "typ_pohybu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        mainTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(mainTable);

        ukazMaterialButton.setBackground(new java.awt.Color(0, 102, 0));
        ukazMaterialButton.setText("Material");
        ukazMaterialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ukazMaterialButtonActionPerformed(evt);
            }
        });

        ukazVydajebutton.setBackground(new java.awt.Color(0, 102, 0));
        ukazVydajebutton.setText("Vydaje");
        ukazVydajebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ukazVydajebuttonActionPerformed(evt);
            }
        });

        vytvorVydajkuButton.setBackground(new java.awt.Color(0, 102, 0));
        vytvorVydajkuButton.setText("Vytvorit vydajku");
        vytvorVydajkuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vytvorVydajkuButtonActionPerformed(evt);
            }
        });

        jPridajKartuMaterialuButton5.setBackground(new java.awt.Color(0, 102, 0));
        jPridajKartuMaterialuButton5.setText("Pridat kartu materialu");
        jPridajKartuMaterialuButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPridajKartuMaterialuButton5ActionPerformed(evt);
            }
        });

        vytvorPrijemkuButton.setBackground(new java.awt.Color(0, 102, 0));
        vytvorPrijemkuButton.setText("Vytvorit prijemku");
        vytvorPrijemkuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vytvorPrijemkuButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Skladnik");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setFocusTraversalPolicyProvider(true);

        uzivatelLable.setBackground(new java.awt.Color(0, 204, 0));
        uzivatelLable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uzivatelLable.setForeground(new java.awt.Color(0, 204, 0));
        uzivatelLable.setText("Uzivatel");

        jVypisyButton1.setBackground(new java.awt.Color(0, 102, 0));
        jVypisyButton1.setText("Vypisy");
        jVypisyButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVypisyButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );

        deleteSelectedButton.setBackground(new java.awt.Color(0, 102, 0));
        deleteSelectedButton.setText("Vymaz oznacene");
        deleteSelectedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSelectedButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(uzivatelLable))
                                .addComponent(ukazVydajebutton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(ukazPrijmiButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(ukazMaterialButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                            .addComponent(jVypisyButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(vytvorPrijemkuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(vytvorVydajkuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jPridajKartuMaterialuButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(deleteSelectedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(247, 247, 247)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uzivatelLable))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ukazPrijmiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ukazVydajebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ukazMaterialButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jVypisyButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vytvorPrijemkuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vytvorVydajkuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jPridajKartuMaterialuButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deleteSelectedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //TO DO pouzivatel ktory je prihlaseny
    private void vytvorPrijemkuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vytvorPrijemkuButtonActionPerformed
        VytvorPrijemkuScreen vytvorPrijemkuScreen = new VytvorPrijemkuScreen();  
        vytvorPrijemkuScreen.uzivatelLabel.setText(this.uzivatelLable.getText());
        vytvorPrijemkuScreen.setVisible(true);
        this.setVisible(false);
         dispose();
        
      
        
    }//GEN-LAST:event_vytvorPrijemkuButtonActionPerformed

    private void vytvorVydajkuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vytvorVydajkuButtonActionPerformed
        VytvorVydajkuScreen vytvorVydajkuScreen = new VytvorVydajkuScreen();    
        vytvorVydajkuScreen.uzivatelLabel.setText(this.uzivatelLable.getText());
        vytvorVydajkuScreen.setVisible(true);
        this.setVisible(false);
     
       
    }//GEN-LAST:event_vytvorVydajkuButtonActionPerformed

    
    
   
    private void ukazPrijmiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ukazPrijmiButtonActionPerformed
      Pouzivatel p = pouzivatelDao.dajPouzivatela(uzivatelLable.getText());
         long idpouzivatela = p.getId(); 
        Calendar cal = new GregorianCalendar();
        int rok = cal.get(Calendar.YEAR);
        
        int mesiac = cal.get(Calendar.MONTH)+1;
        nastavModelDefault();
        tableModel = (DefaultTableModel) mainTable.getModel(); 
        tableModel.getDataVector().removeAllElements();
        tableModel.fireTableDataChanged();
        naplnTabulkuPrijmi(tableModel, prijemkaDao.dajPrijemkyNaMesiac(mesiac, rok, idpouzivatela));
    }//GEN-LAST:event_ukazPrijmiButtonActionPerformed

    private void ukazVydajebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ukazVydajebuttonActionPerformed
         Pouzivatel p = pouzivatelDao.dajPouzivatela(uzivatelLable.getText());
         long idpouzivatela = p.getId(); 
        Calendar cal = new GregorianCalendar();
        int rok = cal.get(Calendar.YEAR);
        
        int mesiac = cal.get(Calendar.MONTH)+1;
        nastavModelDefault();
        tableModel = (DefaultTableModel) mainTable.getModel();         
        tableModel.getDataVector().removeAllElements();
        tableModel.fireTableDataChanged();
        naplnTabulkuVydaje(tableModel, vydajkaDao.dajVydajkyNaMesiac(mesiac, rok, idpouzivatela));
    }//GEN-LAST:event_ukazVydajebuttonActionPerformed

    private void ukazMaterialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ukazMaterialButtonActionPerformed
        nastavModelMaterial();
        tableModel = (DefaultTableModel) mainTable.getModel();         
        tableModel.getDataVector().removeAllElements();
        tableModel.fireTableDataChanged();
        Pouzivatel aktPouz = pouzivatelDao.dajPouzivatela(uzivatelLable.getText());
        long id = aktPouz.getId_sklad();
        naplnTabulkuMaterial(tableModel, materialDao.getAllBySkladId(id));
    }//GEN-LAST:event_ukazMaterialButtonActionPerformed

    private void jPridajKartuMaterialuButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPridajKartuMaterialuButton5ActionPerformed
        PridajKartuMaterialuScreen PKMS = new PridajKartuMaterialuScreen();
        PKMS.uzivatelLabel.setText(this.uzivatelLable.getText());
        PKMS.setVisible(true);
        this.setVisible(false);
        //tu asi dispose netreba nie ? 
      //  dispose();
    }//GEN-LAST:event_jPridajKartuMaterialuButton5ActionPerformed

    private void mainTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainTableMouseClicked
       if(evt.getClickCount()==2){
       int row = mainTable.getSelectedRow();      
       TableModel model = mainTable.getModel();
       String id = model.getValueAt(row, 0).toString();  
           System.out.println(this.model); 
      
       
                      
       
       if(this.model.equals("default")){
       String typPohybu = model.getValueAt(row, 4).toString(); 
       if(typPohybu.equals("1")){
       ZobrazPohybScreen zobrazPrijemkuScreen = new ZobrazPohybScreen();
       zobrazPrijemkuScreen.uzivatelLabel.setText(this.uzivatelLable.getText());
       zobrazPrijemkuScreen.idScreenTextField.setText(id);
       zobrazPrijemkuScreen.naplnTabulkuPrijmi();
       zobrazPrijemkuScreen.setVisible(true);
       this.setVisible(false);
      
       }

       
        if(typPohybu.equals("2")){
       ZobrazPohybScreen zobrazVydajkuScreen = new ZobrazPohybScreen();
       zobrazVydajkuScreen.uzivatelLabel.setText(this.uzivatelLable.getText());
       zobrazVydajkuScreen.idScreenTextField.setText(id);
       zobrazVydajkuScreen.naplnTabulkuVydaje();
       zobrazVydajkuScreen.setVisible(true);
       this.setVisible(false);
     
       }
      }
         if(this.model.equals("material")){
         long idMaterialu= (Long) model.getValueAt(row, 0);
         zobrazKartuMaterialu zobrazKartuMaterialu = new zobrazKartuMaterialu();
         zobrazKartuMaterialu.idMaterialuTextField.setText(idMaterialu+"");
         zobrazKartuMaterialu.uzivatelLabel.setText(this.uzivatelLable.getText());
         zobrazKartuMaterialu.naplnPohybyTable();
      
         zobrazKartuMaterialu.setVisible(true);
         this.setVisible(false);
         
         }

       
       }
    }//GEN-LAST:event_mainTableMouseClicked

    private void jVypisyButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVypisyButton1ActionPerformed
        VypisyScreen VS = new VypisyScreen();
        VS.uzivatelLabel.setText(this.uzivatelLable.getText());
        VS.setVisible(true);
       this.setVisible(false);
       dispose();
        
    }//GEN-LAST:event_jVypisyButton1ActionPerformed

    private void deleteSelectedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSelectedButtonActionPerformed
        int row = mainTable.getSelectedRow();        
        TableModel model = mainTable.getModel();
         if(row==-1){
          JOptionPane.showMessageDialog(null, "Nic nie je oznacene");
          return;
        }
        long id = (Long) model.getValueAt(row, 0);
        long typPohybu = (Long) model.getValueAt(row, 4); 
          if(typPohybu==1){
              prijemkaDao.odstranPrijemku(prijemkaDao.dajPrijemkuById(id));
               pohybMaterialuDao.odstranPohybMaterialuByPrijemkaId(id);
              upravCenyMaterialu(pohybMaterialuDao.getAllPohybyByPrijemkaId(id));
              upravStavMaterialu(pohybMaterialuDao.getAllPohybyByPrijemkaId(id), 2);
              ukazPrijmiButtonActionPerformed(evt);
          }
          if(typPohybu==2){
          vydajkaDao.odstranVydajku(vydajkaDao.dajVydajkaById(id));
            pohybMaterialuDao.odstranPohybMaterialuByVydajkaId(id);
           upravStavMaterialu(pohybMaterialuDao.getAllPohybyByVydajkaId(id), 1);
              ukazVydajebuttonActionPerformed(evt);
          }
    }//GEN-LAST:event_deleteSelectedButtonActionPerformed

     private void naplnTabulkuPrijmi(DefaultTableModel model, List<Prijemka> prijmi){
    for(Prijemka prijemka : prijmi){
       model.addRow(new Object[]{prijemka.getId(),prijemka.getCena(),prijemka.getId_pouzivatel(),prijemka.getDatum(),prijemka.getTypPohybu()});
    }
    }
    
 
   
    
    
      private void naplnTabulkuVydaje(DefaultTableModel model, List<Vydajka> vydajky){
    for(Vydajka vydajka : vydajky){
       model.addRow(new Object[]{vydajka.getId(),vydajka.getCena(),vydajka.getId_pouzivatel(),vydajka.getDatum(),vydajka.getTyp_pohybu()});
    }
    }
  
       private void naplnTabulkuMaterial(DefaultTableModel model, List<Material> materials){
          
        for(Material material : materials){
      model.addRow(new Object[]{material.getId(),material.getNazov(),material.getStav(),new DecimalFormat("##.##").format(material.getCena()),material.getId_sklad()});
    }
    }
      
     
      private void nastavModelMaterial(){
          model="material";
          String[] columns = {"id","nazov","stav","cena","id_sklad"};
          DefaultTableModel model = new DefaultTableModel(columns,0){
          @Override
          public boolean isCellEditable(int row, int column){
          return false;
          }
          
          };  
          
            mainTable.setModel(model ); 
         
            

      }
      
      private void nastavModelDefault(){
          model="default";
          String[] columns = {"id","cena","id_pouzivatela","datum","typ_pohybu"};
            DefaultTableModel model = new DefaultTableModel(columns,0){
          @Override
          public boolean isCellEditable(int row, int column){
          return false;
          }
          
          };
            mainTable.setModel(model); 
      }
      
      public void upravStavMaterialu(List<PohybMaterialu> pohyby,int typPohybu){
      long idMaterialu;
     double pocet;         
     for (int i = 0 ; i < pohyby.size() ; i++) {
        idMaterialu =  pohyby.get(i).getId_materialu();
        pocet = pohyby.get(i).getPocet();
           materialDao.upravStavMaterial(idMaterialu, pocet,typPohybu);    
          
    } 
    
  
    }
      
      
      
      public void upravCenyMaterialu(List<PohybMaterialu> pohyby){ 
      long idMaterialu;
      double pocet;
      double cena;
    for (int i = 0 ; i < pohyby.size() ; i++) {
        idMaterialu =  pohyby.get(i).getId_materialu();
        pocet = pohyby.get(i).getPocet();
        cena = pohyby.get(i).getCena();
        materialDao.upravCenuMaterialu(idMaterialu, upravCenuMaterialu(idMaterialu, cena, pocet));       
    }  
    }
      
      public double upravCenuMaterialu(long idMaterialu, double cena, double pocet){    
    double cenaPoUprave =0;
    double sucetPoctov = 0;
    double sucetSucinov = 0;
    List<PohybMaterialu> pohyby = pohybMaterialuDao.getPohybyByMaterialId(idMaterialu);
    for(PohybMaterialu pohyb : pohyby){
        System.out.println(pohyb.toString());
       sucetSucinov += (pohyb.getCena()*pohyb.getPocet());
       sucetPoctov += pohyb.getPocet();    
    }
    sucetSucinov += cena*pocet;
    sucetPoctov +=pocet;
    
    cenaPoUprave=sucetSucinov/sucetPoctov;
    
    
    return cenaPoUprave;
    
    }
      
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteSelectedButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jPridajKartuMaterialuButton5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jVypisyButton1;
    private javax.swing.JTable mainTable;
    public javax.swing.JButton ukazMaterialButton;
    private javax.swing.JButton ukazPrijmiButton;
    private javax.swing.JButton ukazVydajebutton;
    public javax.swing.JLabel uzivatelLable;
    private javax.swing.JButton vytvorPrijemkuButton;
    private javax.swing.JButton vytvorVydajkuButton;
    // End of variables declaration//GEN-END:variables
}
