/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ics.upjs.sk.paz1c.skladnik.gui;

import Factory.ObjectFactory;
import dao.MaterialDao;
import dao.PouzivatelDao;
import dao.PrijemkaDao;
import dao.VydajkaDao;
import ics.upjs.sk.paz1c.skladnik.entity.Pouzivatel;
import ics.upjs.sk.paz1c.skladnik.entity.Prijemka;
import ics.upjs.sk.paz1c.skladnik.entity.Vydajka;
import ics.upjs.sk.paz1c.skladnik.entity.Material;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcel
 */
public class MainScreen extends javax.swing.JFrame {

    PrijemkaDao prijemkaDao = ObjectFactory.INSTANCE.getPrijemkadDao();
    PouzivatelDao pouzivatelDao =ObjectFactory.INSTANCE.getPouzivatelDao();
    VydajkaDao vydajkaDao = ObjectFactory.INSTANCE.getVydajkaDao();
    MaterialDao materialDao = ObjectFactory.INSTANCE.getMaterialDao();
    DefaultTableModel tableModel; 

    
    public MainScreen() {
        initComponents(); 
        tableModel = (DefaultTableModel) mainTable.getModel();           
        naplnTabulkuPrijmi(tableModel, prijemkaDao.getAll());
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ukazPrijmiButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        ukazMaterialButton = new javax.swing.JButton();
        ukazVydajebutton = new javax.swing.JButton();
        vytvorVydajkuButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        vytvorPrijemkuButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ukazPrijmiButton.setText("Prijmy");
        ukazPrijmiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ukazPrijmiButtonActionPerformed(evt);
            }
        });

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "cena", "id_pouzivatela", "datum"
            }
        ));
        jScrollPane2.setViewportView(mainTable);

        ukazMaterialButton.setText("Material");
        ukazMaterialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ukazMaterialButtonActionPerformed(evt);
            }
        });

        ukazVydajebutton.setText("Vydaje");
        ukazVydajebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ukazVydajebuttonActionPerformed(evt);
            }
        });

        vytvorVydajkuButton.setText("Vytvorit vydajku");
        vytvorVydajkuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vytvorVydajkuButtonActionPerformed(evt);
            }
        });

        jButton5.setText("Pridat kartu materialu");

        vytvorPrijemkuButton.setText("Vytvorit prijemku");
        vytvorPrijemkuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vytvorPrijemkuButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Skladnik");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setFocusTraversalPolicyProvider(true);

        jLabel1.setText("Uzivatel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(vytvorPrijemkuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addComponent(vytvorVydajkuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addGap(297, 297, 297)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ukazPrijmiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ukazVydajebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ukazMaterialButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ukazPrijmiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ukazVydajebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ukazMaterialButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vytvorVydajkuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vytvorPrijemkuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //TO DO pouzivatel ktory je prihlaseny
    private void vytvorPrijemkuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vytvorPrijemkuButtonActionPerformed
        String timeStamp = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(Calendar.getInstance().getTime());       
        Pouzivatel pouzivatel = pouzivatelDao.dajPouzivatela("pista");
        Prijemka prijemka = new Prijemka();        
        prijemka.setId_pouzivatel(pouzivatel.getId());     
        prijemka.setDatum(timeStamp);  
        prijemkaDao.pridajPrijemka(prijemka);       
        VytvorPrijemkuScreen vytvorPrijemkuScreen = new VytvorPrijemkuScreen();                       
        vytvorPrijemkuScreen.setVisible(true);
        this.setVisible(false);
        dispose();
        System.out.println(prijemkaDao.getAll()
        );
      
        
    }//GEN-LAST:event_vytvorPrijemkuButtonActionPerformed

    private void vytvorVydajkuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vytvorVydajkuButtonActionPerformed
       String timeStamp = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(Calendar.getInstance().getTime());       
        Pouzivatel pouzivatel = pouzivatelDao.dajPouzivatela("pista");
        Vydajka vydajka = new Vydajka();        
        vydajka.setId_pouzivatel(pouzivatel.getId());     
        vydajka.setDatum(timeStamp);  
        vydajkaDao.pridajVydajku(vydajka);       
        VytvorVydajkuScreen vytvorVydajkuScreen = new VytvorVydajkuScreen();                       
        vytvorVydajkuScreen.setVisible(true);
        this.setVisible(false);
        dispose();
        System.out.println(vydajkaDao.getAll());
    }//GEN-LAST:event_vytvorVydajkuButtonActionPerformed

    private void ukazPrijmiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ukazPrijmiButtonActionPerformed
        nastavModelDefault();
        tableModel = (DefaultTableModel) mainTable.getModel(); 
        tableModel.getDataVector().removeAllElements();
        tableModel.fireTableDataChanged();
        naplnTabulkuPrijmi(tableModel, prijemkaDao.getAll());
    }//GEN-LAST:event_ukazPrijmiButtonActionPerformed

    private void ukazVydajebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ukazVydajebuttonActionPerformed
        nastavModelDefault();
        tableModel = (DefaultTableModel) mainTable.getModel();         
        tableModel.getDataVector().removeAllElements();
        tableModel.fireTableDataChanged();
        naplnTabulkuVydaje(tableModel, vydajkaDao.getAll());
    }//GEN-LAST:event_ukazVydajebuttonActionPerformed

    private void ukazMaterialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ukazMaterialButtonActionPerformed
        nastavModelMaterial();
        tableModel = (DefaultTableModel) mainTable.getModel();         
        tableModel.getDataVector().removeAllElements();
        tableModel.fireTableDataChanged();
        naplnTabulkuMaterial(tableModel, materialDao.getAll());
    }//GEN-LAST:event_ukazMaterialButtonActionPerformed

    private void naplnTabulkuPrijmi(DefaultTableModel model, List<Prijemka> prijemky){
    for(Prijemka prijemka : prijemky){
       model.addRow(new Object[]{prijemka.getId(),prijemka.getCena(),prijemka.getId_pouzivatel(),prijemka.getDatum()});
    }
    }
    
      private void naplnTabulkuVydaje(DefaultTableModel model, List<Vydajka> vydajky){
    for(Vydajka vydajka : vydajky){
       model.addRow(new Object[]{vydajka.getId(),vydajka.getCena(),vydajka.getId_pouzivatel(),vydajka.getDatum()});
    }
    }
  
       private void naplnTabulkuMaterial(DefaultTableModel model, List<Material> materials){
          
        for(Material material : materials){
      model.addRow(new Object[]{material.getId(),material.getNazov(),material.getStav(),material.getCena(),material.getId_sklad()});
    }
    }
      
     
      private void nastavModelMaterial(){
          String[] columns = {"id","nazov","stav","cena","id_sklad"};
          DefaultTableModel model = new DefaultTableModel(columns,0);
            mainTable.setModel(model); 
         

      }
      
      private void nastavModelDefault(){
          String[] columns = {"id","cena","id_pouzivatela","datum"};
          DefaultTableModel model = new DefaultTableModel(columns,0);
            mainTable.setModel(model); 
            
           

      }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable mainTable;
    private javax.swing.JButton ukazMaterialButton;
    private javax.swing.JButton ukazPrijmiButton;
    private javax.swing.JButton ukazVydajebutton;
    private javax.swing.JButton vytvorPrijemkuButton;
    private javax.swing.JButton vytvorVydajkuButton;
    // End of variables declaration//GEN-END:variables
}
