/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ics.upjs.sk.paz1c.skladnik.gui;

import Factory.ObjectFactory;
import dao.PrijemkaDao;
import ics.upjs.sk.paz1c.skladnik.entity.Prijemka;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Daniel
 */
public class VypisyPrijemkyScreen extends javax.swing.JFrame {
 DefaultTableModel tableModel; 
 PrijemkaDao prijemkaDao = ObjectFactory.INSTANCE.getPrijemkadDao();
    /**
     * Creates new form VypisyPrijemkyScreen
     */
    public VypisyPrijemkyScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jZobrazdnesneprijemkyButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMesiacComboBox1 = new javax.swing.JComboBox<>();
        jZobrazPrijemkyZamesiacButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jROKComboBox1 = new javax.swing.JComboBox<>();
        jZobrazPrijemkyRokButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPrijemkyNaDenRokComboBox2 = new javax.swing.JComboBox<>();
        jPrijemkyNaDenMesiacComboBox3 = new javax.swing.JComboBox<>();
        jPrijemkyNaDenDenComboBox1 = new javax.swing.JComboBox<>();
        jZobrazPrijenkyNaDenButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        jspatButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        uzivatelLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Dnešné príjemky :");

        jZobrazdnesneprijemkyButton1.setBackground(new java.awt.Color(0, 102, 0));
        jZobrazdnesneprijemkyButton1.setText("Zobraz ");
        jZobrazdnesneprijemkyButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jZobrazdnesneprijemkyButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Príjemky za mesiac:");

        jMesiacComboBox1.setBackground(new java.awt.Color(51, 51, 51));
        jMesiacComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jZobrazPrijemkyZamesiacButton1.setBackground(new java.awt.Color(0, 102, 0));
        jZobrazPrijemkyZamesiacButton1.setText("Zobraz");
        jZobrazPrijemkyZamesiacButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jZobrazPrijemkyZamesiacButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Príjemky za rok :");

        jROKComboBox1.setBackground(new java.awt.Color(51, 51, 51));
        jROKComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017" }));

        jZobrazPrijemkyRokButton1.setBackground(new java.awt.Color(0, 102, 0));
        jZobrazPrijemkyRokButton1.setText("Zobraz");
        jZobrazPrijemkyRokButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jZobrazPrijemkyRokButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Príjemky na deň :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Rok");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Mesiac");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Deň");

        jPrijemkyNaDenRokComboBox2.setBackground(new java.awt.Color(51, 51, 51));
        jPrijemkyNaDenRokComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017" }));

        jPrijemkyNaDenMesiacComboBox3.setBackground(new java.awt.Color(51, 51, 51));
        jPrijemkyNaDenMesiacComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jPrijemkyNaDenDenComboBox1.setBackground(new java.awt.Color(51, 51, 51));
        jPrijemkyNaDenDenComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jZobrazPrijenkyNaDenButton1.setBackground(new java.awt.Color(0, 102, 0));
        jZobrazPrijenkyNaDenButton1.setText("Zobraz");
        jZobrazPrijenkyNaDenButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jZobrazPrijenkyNaDenButton1ActionPerformed(evt);
            }
        });

        mainTable.setBackground(new java.awt.Color(0, 204, 102));
        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Cena", "Datum"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        mainTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(mainTable);

        jspatButton1.setBackground(new java.awt.Color(0, 102, 0));
        jspatButton1.setText("Spat");
        jspatButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jspatButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Príjemky");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 373, Short.MAX_VALUE)
        );

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));

        jSeparator2.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));

        jSeparator3.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));

        uzivatelLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uzivatelLabel.setForeground(new java.awt.Color(0, 204, 0));
        uzivatelLabel.setText("Uzivatel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jZobrazdnesneprijemkyButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jMesiacComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                                .addComponent(jZobrazPrijemkyZamesiacButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jROKComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jZobrazPrijemkyRokButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jPrijemkyNaDenRokComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(25, 25, 25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jPrijemkyNaDenMesiacComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPrijemkyNaDenDenComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7)))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jZobrazPrijenkyNaDenButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(uzivatelLabel)
                                .addGap(176, 176, 176)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jspatButton1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jZobrazdnesneprijemkyButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jMesiacComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jZobrazPrijemkyZamesiacButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jROKComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jZobrazPrijemkyRokButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPrijemkyNaDenMesiacComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPrijemkyNaDenDenComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPrijemkyNaDenRokComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jZobrazPrijenkyNaDenButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jspatButton1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(uzivatelLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
                                    
       
    
    private void jZobrazPrijemkyRokButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jZobrazPrijemkyRokButton1ActionPerformed
          int rok = Integer.parseInt(jROKComboBox1.getSelectedItem().toString());
        
        nastavModelDefault();
        tableModel = (DefaultTableModel) mainTable.getModel(); 
        tableModel.getDataVector().removeAllElements();
        tableModel.fireTableDataChanged();
        naplnTabulkuPrijmi(tableModel, prijemkaDao.dajPrijemkyNaRok(rok));
    }//GEN-LAST:event_jZobrazPrijemkyRokButton1ActionPerformed

    private void jZobrazdnesneprijemkyButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jZobrazdnesneprijemkyButton1ActionPerformed
         nastavModelDefault();
        tableModel = (DefaultTableModel) mainTable.getModel(); 
        tableModel.getDataVector().removeAllElements();
        tableModel.fireTableDataChanged();
        naplnTabulkuPrijmi(tableModel, prijemkaDao.dajDnesneOPrijemky());
    
    }//GEN-LAST:event_jZobrazdnesneprijemkyButton1ActionPerformed

    private void jZobrazPrijenkyNaDenButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jZobrazPrijenkyNaDenButton1ActionPerformed
        int rok = Integer.parseInt(jPrijemkyNaDenRokComboBox2.getSelectedItem().toString());
        int mesiac = Integer.parseInt(jPrijemkyNaDenMesiacComboBox3.getSelectedItem().toString());
        int den = Integer.parseInt(jPrijemkyNaDenDenComboBox1.getSelectedItem().toString());
        
        nastavModelDefault();
        tableModel = (DefaultTableModel) mainTable.getModel(); 
        tableModel.getDataVector().removeAllElements();
        tableModel.fireTableDataChanged();
        naplnTabulkuPrijmi(tableModel, prijemkaDao.dajPrijemkuNaDatum(rok, mesiac, den));
    }//GEN-LAST:event_jZobrazPrijenkyNaDenButton1ActionPerformed

    private void jZobrazPrijemkyZamesiacButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jZobrazPrijemkyZamesiacButton1ActionPerformed
        Calendar cal = new GregorianCalendar();
        int rok = cal.get(Calendar.YEAR);
        
        int mesiac = Integer.parseInt(jMesiacComboBox1.getSelectedItem().toString());
        
        
        nastavModelDefault();
        tableModel = (DefaultTableModel) mainTable.getModel(); 
        tableModel.getDataVector().removeAllElements();
        tableModel.fireTableDataChanged();
        naplnTabulkuPrijmi(tableModel, prijemkaDao.dajPrijemkyNaMesiac(mesiac,rok));
    }//GEN-LAST:event_jZobrazPrijemkyZamesiacButton1ActionPerformed

    private void jspatButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jspatButton1ActionPerformed
       MainScreen ms = new MainScreen();
       ms.uzivatelLable.setText(this.uzivatelLabel.getText());
       ms.setVisible(true);
       this.setVisible(false);
       dispose();
    }//GEN-LAST:event_jspatButton1ActionPerformed

    private void mainTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainTableMouseClicked
       if(evt.getClickCount()==2){
       int row = mainTable.getSelectedRow();      
       TableModel model = mainTable.getModel();
       String id = model.getValueAt(row, 0).toString();         
       
       
       ZobrazPohybScreen zobrazPrijemkuScreen = new ZobrazPohybScreen();
       zobrazPrijemkuScreen.uzivatelLabel.setText(this.uzivatelLabel.getText());
       zobrazPrijemkuScreen.idScreenTextField.setText(id);
       zobrazPrijemkuScreen.naplnTabulkuPrijmi();
       zobrazPrijemkuScreen.setVisible(true);
       this.setVisible(false);
       dispose();
       }
       
    }//GEN-LAST:event_mainTableMouseClicked

     private void naplnTabulkuPrijmi(DefaultTableModel model, List<Prijemka> prijmi){
    for(Prijemka prijemka : prijmi){
       model.addRow(new Object[]{prijemka.getId(),prijemka.getCena(),prijemka.getDatum()});
    }
    }
    
    
    private void nastavModelDefault(){
          String[] columns = {"id","cena","datum",};
            DefaultTableModel model = new DefaultTableModel(columns,0){
          @Override
          public boolean isCellEditable(int row, int column){
          return false;
          }
          
          };
            mainTable.setModel(model); 
            
           

      }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VypisyPrijemkyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VypisyPrijemkyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VypisyPrijemkyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VypisyPrijemkyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VypisyPrijemkyScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox<String> jMesiacComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jPrijemkyNaDenDenComboBox1;
    private javax.swing.JComboBox<String> jPrijemkyNaDenMesiacComboBox3;
    private javax.swing.JComboBox<String> jPrijemkyNaDenRokComboBox2;
    private javax.swing.JComboBox<String> jROKComboBox1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jZobrazPrijemkyRokButton1;
    private javax.swing.JButton jZobrazPrijemkyZamesiacButton1;
    private javax.swing.JButton jZobrazPrijenkyNaDenButton1;
    private javax.swing.JButton jZobrazdnesneprijemkyButton1;
    private javax.swing.JButton jspatButton1;
    private javax.swing.JTable mainTable;
    public javax.swing.JLabel uzivatelLabel;
    // End of variables declaration//GEN-END:variables
}
