/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ics.upjs.sk.paz1c.skladnik.gui;

import Factory.ObjectFactory;
import dao.VydajkaDao;
import ics.upjs.sk.paz1c.skladnik.entity.Vydajka;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel
 */
public class VypisyVydajkyScreen extends javax.swing.JFrame {
DefaultTableModel tableModel; 
 VydajkaDao vydajkaDao = ObjectFactory.INSTANCE.getVydajkaDao();
    /**
     * Creates new form VypisyVydajkyScreen
     */
    public VypisyVydajkyScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jZobrazDnesneVydajkyButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jZobrazVydajkyZaMesiacButton1 = new javax.swing.JButton();
        jMesiacComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jZobrazVydajkyZaRokButton1 = new javax.swing.JButton();
        jRokComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jVydajkyNaDenRokComboBox2 = new javax.swing.JComboBox<>();
        jVydajkyNaDedMesiacComboBox1 = new javax.swing.JComboBox<>();
        jVydajkyNaDenDenComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        jZobrazVydajkyNaDenButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Dnesne vydajky :");

        jZobrazDnesneVydajkyButton1.setText("Zobraz");
        jZobrazDnesneVydajkyButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jZobrazDnesneVydajkyButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Vydajky za mesiac :");

        jZobrazVydajkyZaMesiacButton1.setText("Zobraz");
        jZobrazVydajkyZaMesiacButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jZobrazVydajkyZaMesiacButton1ActionPerformed(evt);
            }
        });

        jMesiacComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel3.setText("Vydajky za rok :");

        jZobrazVydajkyZaRokButton1.setText("Zobraz");
        jZobrazVydajkyZaRokButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jZobrazVydajkyZaRokButton1ActionPerformed(evt);
            }
        });

        jRokComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017" }));

        jLabel4.setText("Vydajky na den");

        jLabel5.setText("Rok");

        jLabel6.setText("Mesiac");

        jLabel7.setText("Den");

        jVydajkyNaDenRokComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2016" }));

        jVydajkyNaDedMesiacComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jVydajkyNaDenDenComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Cena", "Datum"
            }
        ));
        jScrollPane1.setViewportView(mainTable);

        jZobrazVydajkyNaDenButton1.setText("Zobraz");
        jZobrazVydajkyNaDenButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jZobrazVydajkyNaDenButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jZobrazDnesneVydajkyButton1)
                        .addGap(176, 176, 176)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jMesiacComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jZobrazVydajkyZaMesiacButton1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jRokComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jZobrazVydajkyZaRokButton1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(jLabel5)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jZobrazVydajkyNaDenButton1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jVydajkyNaDenRokComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(jVydajkyNaDedMesiacComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(50, 50, 50)
                                .addComponent(jVydajkyNaDenDenComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jZobrazDnesneVydajkyButton1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jZobrazVydajkyZaMesiacButton1)
                            .addComponent(jVydajkyNaDenRokComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jVydajkyNaDedMesiacComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jVydajkyNaDenDenComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jMesiacComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jZobrazVydajkyNaDenButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRokComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jZobrazVydajkyZaRokButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jZobrazDnesneVydajkyButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jZobrazDnesneVydajkyButton1ActionPerformed
             nastavModelDefault();
        tableModel = (DefaultTableModel) mainTable.getModel(); 
        tableModel.getDataVector().removeAllElements();
        tableModel.fireTableDataChanged();
        naplnTabulkuPrijmi(tableModel, vydajkaDao.dajDnesneVydajky());
    }//GEN-LAST:event_jZobrazDnesneVydajkyButton1ActionPerformed

    private void jZobrazVydajkyZaMesiacButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jZobrazVydajkyZaMesiacButton1ActionPerformed
         Calendar cal = new GregorianCalendar();
        int rok = cal.get(Calendar.YEAR);
        
        int mesiac = Integer.parseInt(jMesiacComboBox1.getSelectedItem().toString());
        
        
        nastavModelDefault();
        tableModel = (DefaultTableModel) mainTable.getModel(); 
        tableModel.getDataVector().removeAllElements();
        tableModel.fireTableDataChanged();
        naplnTabulkuPrijmi(tableModel, vydajkaDao.dajVydajkyNaMesiac(mesiac,rok));
        
    }//GEN-LAST:event_jZobrazVydajkyZaMesiacButton1ActionPerformed

    private void jZobrazVydajkyZaRokButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jZobrazVydajkyZaRokButton1ActionPerformed
         int rok = Integer.parseInt(jRokComboBox1.getSelectedItem().toString());
        
        nastavModelDefault();
        tableModel = (DefaultTableModel) mainTable.getModel(); 
        tableModel.getDataVector().removeAllElements();
        tableModel.fireTableDataChanged();
        naplnTabulkuPrijmi(tableModel, vydajkaDao.dajVydajkyNaRok(rok));
    }//GEN-LAST:event_jZobrazVydajkyZaRokButton1ActionPerformed

    private void jZobrazVydajkyNaDenButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jZobrazVydajkyNaDenButton1ActionPerformed
       int rok = Integer.parseInt(jVydajkyNaDenRokComboBox2.getSelectedItem().toString());
        int mesiac = Integer.parseInt(jVydajkyNaDedMesiacComboBox1.getSelectedItem().toString());
        int den = Integer.parseInt(jVydajkyNaDenDenComboBox1.getSelectedItem().toString());
        
        nastavModelDefault();
        tableModel = (DefaultTableModel) mainTable.getModel(); 
        tableModel.getDataVector().removeAllElements();
        tableModel.fireTableDataChanged();
        naplnTabulkuPrijmi(tableModel, vydajkaDao.dajVydajkuNaDatum(rok, mesiac, den));
    }//GEN-LAST:event_jZobrazVydajkyNaDenButton1ActionPerformed
    private void naplnTabulkuPrijmi(DefaultTableModel model, List<Vydajka> vydaje){
    for(Vydajka vydajka : vydaje){
       model.addRow(new Object[]{vydajka.getId(),vydajka.getCena(),vydajka.getDatum()});
    }
    }
    
    
    private void nastavModelDefault(){
          String[] columns = {"id","cena","datum",};
            DefaultTableModel model = new DefaultTableModel(columns,0){
          @Override
          public boolean isCellEditable(int row, int column){
          return false;
          }
          
          };
            mainTable.setModel(model); 
            
           

      }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VypisyVydajkyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VypisyVydajkyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VypisyVydajkyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VypisyVydajkyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VypisyVydajkyScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> jMesiacComboBox1;
    private javax.swing.JComboBox<String> jRokComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jVydajkyNaDedMesiacComboBox1;
    private javax.swing.JComboBox<String> jVydajkyNaDenDenComboBox1;
    private javax.swing.JComboBox<String> jVydajkyNaDenRokComboBox2;
    private javax.swing.JButton jZobrazDnesneVydajkyButton1;
    private javax.swing.JButton jZobrazVydajkyNaDenButton1;
    private javax.swing.JButton jZobrazVydajkyZaMesiacButton1;
    private javax.swing.JButton jZobrazVydajkyZaRokButton1;
    private javax.swing.JTable mainTable;
    // End of variables declaration//GEN-END:variables
}
