/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ics.upjs.sk.paz1c.skladnik.gui;

import Factory.ObjectFactory;
import dao.PrijemkaDao;
import ics.upjs.sk.paz1c.skladnik.entity.Prijemka;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel
 */
public class VypisyPrijemkyScreen extends javax.swing.JFrame {
 DefaultTableModel tableModel; 
 PrijemkaDao prijemkaDao = ObjectFactory.INSTANCE.getPrijemkadDao();
    /**
     * Creates new form VypisyPrijemkyScreen
     */
    public VypisyPrijemkyScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jZobrazdnesneprijemkyButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMesiacComboBox1 = new javax.swing.JComboBox<>();
        jZobrazPrijemkyZamesiacButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jROKComboBox1 = new javax.swing.JComboBox<>();
        jZobrazPrijemkyRokButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPrijemkyNaDenRokComboBox2 = new javax.swing.JComboBox<>();
        jPrijemkyNaDenMesiacComboBox3 = new javax.swing.JComboBox<>();
        jPrijemkyNaDenDenComboBox1 = new javax.swing.JComboBox<>();
        jZobrazPrijenkyNaDenButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Dnešné príjemky :");

        jZobrazdnesneprijemkyButton1.setText("Zobraz ");
        jZobrazdnesneprijemkyButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jZobrazdnesneprijemkyButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Príjemky za mesiac:");

        jMesiacComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jZobrazPrijemkyZamesiacButton1.setText("Zobraz");
        jZobrazPrijemkyZamesiacButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jZobrazPrijemkyZamesiacButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Príjemky za rok");

        jROKComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017" }));

        jZobrazPrijemkyRokButton1.setText("Zobraz");
        jZobrazPrijemkyRokButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jZobrazPrijemkyRokButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Príjemky na den");

        jLabel5.setText("ROK");

        jLabel6.setText("Mesiac");

        jLabel7.setText("Den");

        jPrijemkyNaDenRokComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017" }));

        jPrijemkyNaDenMesiacComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jPrijemkyNaDenMesiacComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrijemkyNaDenMesiacComboBox3ActionPerformed(evt);
            }
        });

        jPrijemkyNaDenDenComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jZobrazPrijenkyNaDenButton1.setText("Zobraz");
        jZobrazPrijenkyNaDenButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jZobrazPrijenkyNaDenButton1ActionPerformed(evt);
            }
        });

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Cena", "Datum"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(mainTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMesiacComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jROKComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jZobrazdnesneprijemkyButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jZobrazPrijemkyZamesiacButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(131, 131, 131)
                                .addComponent(jZobrazPrijenkyNaDenButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jZobrazPrijemkyRokButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jPrijemkyNaDenRokComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPrijemkyNaDenMesiacComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPrijemkyNaDenDenComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(49, 49, 49)
                .addComponent(jLabel6)
                .addGap(44, 44, 44)
                .addComponent(jLabel7)
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jZobrazdnesneprijemkyButton1))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPrijemkyNaDenRokComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPrijemkyNaDenMesiacComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPrijemkyNaDenDenComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jZobrazPrijemkyZamesiacButton1)
                            .addComponent(jZobrazPrijenkyNaDenButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jMesiacComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jROKComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jZobrazPrijemkyRokButton1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 19, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jZobrazPrijemkyRokButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jZobrazPrijemkyRokButton1ActionPerformed
          int rok = Integer.parseInt(jROKComboBox1.getSelectedItem().toString());
        
        nastavModelDefault();
        tableModel = (DefaultTableModel) mainTable.getModel(); 
        tableModel.getDataVector().removeAllElements();
        tableModel.fireTableDataChanged();
        naplnTabulkuPrijmi(tableModel, prijemkaDao.dajPrijemkyNaRok(rok));
    }//GEN-LAST:event_jZobrazPrijemkyRokButton1ActionPerformed

    private void jPrijemkyNaDenMesiacComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrijemkyNaDenMesiacComboBox3ActionPerformed
        nastavModelDefault();
        tableModel = (DefaultTableModel) mainTable.getModel(); 
        tableModel.getDataVector().removeAllElements();
        tableModel.fireTableDataChanged();
        naplnTabulkuPrijmi(tableModel, prijemkaDao.dajDnesneOPrijemky());
    }//GEN-LAST:event_jPrijemkyNaDenMesiacComboBox3ActionPerformed

    private void jZobrazdnesneprijemkyButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jZobrazdnesneprijemkyButton1ActionPerformed
         nastavModelDefault();
        tableModel = (DefaultTableModel) mainTable.getModel(); 
        tableModel.getDataVector().removeAllElements();
        tableModel.fireTableDataChanged();
        naplnTabulkuPrijmi(tableModel, prijemkaDao.dajDnesneOPrijemky());
    
    }//GEN-LAST:event_jZobrazdnesneprijemkyButton1ActionPerformed

    private void jZobrazPrijenkyNaDenButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jZobrazPrijenkyNaDenButton1ActionPerformed
        int rok = Integer.parseInt(jPrijemkyNaDenRokComboBox2.getSelectedItem().toString());
        int mesiac = Integer.parseInt(jPrijemkyNaDenMesiacComboBox3.getSelectedItem().toString());
        int den = Integer.parseInt(jPrijemkyNaDenDenComboBox1.getSelectedItem().toString());
        
        nastavModelDefault();
        tableModel = (DefaultTableModel) mainTable.getModel(); 
        tableModel.getDataVector().removeAllElements();
        tableModel.fireTableDataChanged();
        naplnTabulkuPrijmi(tableModel, prijemkaDao.dajPrijemkuNaDatum(rok, mesiac, den));
    }//GEN-LAST:event_jZobrazPrijenkyNaDenButton1ActionPerformed

    private void jZobrazPrijemkyZamesiacButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jZobrazPrijemkyZamesiacButton1ActionPerformed
        Calendar cal = new GregorianCalendar();
        int rok = cal.get(Calendar.YEAR);
        
        int mesiac = Integer.parseInt(jMesiacComboBox1.getSelectedItem().toString());
        
        
        nastavModelDefault();
        tableModel = (DefaultTableModel) mainTable.getModel(); 
        tableModel.getDataVector().removeAllElements();
        tableModel.fireTableDataChanged();
        naplnTabulkuPrijmi(tableModel, prijemkaDao.dajPrijemkyNaMesiac(mesiac,rok));
    }//GEN-LAST:event_jZobrazPrijemkyZamesiacButton1ActionPerformed

     private void naplnTabulkuPrijmi(DefaultTableModel model, List<Prijemka> prijmi){
    for(Prijemka prijemka : prijmi){
       model.addRow(new Object[]{prijemka.getId(),prijemka.getCena(),prijemka.getDatum()});
    }
    }
    
    
    private void nastavModelDefault(){
          String[] columns = {"id","cena","datum",};
            DefaultTableModel model = new DefaultTableModel(columns,0){
          @Override
          public boolean isCellEditable(int row, int column){
          return false;
          }
          
          };
            mainTable.setModel(model); 
            
           

      }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VypisyPrijemkyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VypisyPrijemkyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VypisyPrijemkyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VypisyPrijemkyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VypisyPrijemkyScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> jMesiacComboBox1;
    private javax.swing.JComboBox<String> jPrijemkyNaDenDenComboBox1;
    private javax.swing.JComboBox<String> jPrijemkyNaDenMesiacComboBox3;
    private javax.swing.JComboBox<String> jPrijemkyNaDenRokComboBox2;
    private javax.swing.JComboBox<String> jROKComboBox1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jZobrazPrijemkyRokButton1;
    private javax.swing.JButton jZobrazPrijemkyZamesiacButton1;
    private javax.swing.JButton jZobrazPrijenkyNaDenButton1;
    private javax.swing.JButton jZobrazdnesneprijemkyButton1;
    private javax.swing.JTable mainTable;
    // End of variables declaration//GEN-END:variables
}
