/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ics.upjs.sk.paz1c.skladnik.gui;

import Factory.ObjectFactory;
import dao.MaterialDao;
import dao.MysqlPrijemkaDao;
import dao.PohybMaterialuDao;
import dao.PouzivatelDao;
import dao.PrijemkaDao;
import ics.upjs.sk.paz1c.skladnik.entity.Material;
import ics.upjs.sk.paz1c.skladnik.entity.PohybMaterialu;
import ics.upjs.sk.paz1c.skladnik.entity.Pouzivatel;
import ics.upjs.sk.paz1c.skladnik.entity.Prijemka;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Marcel
 */
public class VytvorPrijemkuScreen extends javax.swing.JFrame {
    
       PrijemkaDao prijemkaDao = ObjectFactory.INSTANCE.getPrijemkadDao();
       PohybMaterialuDao pohybMaterialuDao = ObjectFactory.INSTANCE.getPohybMaterialuDao();
       MaterialDao materialDao = ObjectFactory.INSTANCE.getMaterialDao();
       PouzivatelDao pouzivatelDao = ObjectFactory.INSTANCE.getPouzivatelDao();
       private int idPrijemky=prijemkaDao.getLastId()+1;
       private Pouzivatel pouzivatel;
       private List<PohybMaterialu> pohyby;
   
      
      
    /**
     * Creates new form VytvorPrijemkuScreen
     */
    public VytvorPrijemkuScreen() {
               
        initComponents();                
        idTextField.setText(Integer.toString(idPrijemky));
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idLabel = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        pocetLabel = new javax.swing.JLabel();
        idMaterialuLabel = new javax.swing.JLabel();
        idMaterualuTextField = new javax.swing.JTextField();
        pocetTextField = new javax.swing.JTextField();
        cenaLabel = new javax.swing.JLabel();
        cenaTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        materialTable = new javax.swing.JTable();
        potvrdPrijemkuButton = new javax.swing.JButton();
        stornoButton = new javax.swing.JButton();
        pridajMaterialuButton = new javax.swing.JButton();
        cenaSpoluTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        uzivatelLabel = new javax.swing.JLabel();
        vymazPohybMaterialuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        idLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idLabel.setForeground(new java.awt.Color(51, 51, 51));
        idLabel.setText("ID:");

        idTextField.setEditable(false);
        idTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        pocetLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pocetLabel.setForeground(new java.awt.Color(51, 51, 51));
        pocetLabel.setText("Pocet:");

        idMaterialuLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idMaterialuLabel.setForeground(new java.awt.Color(51, 51, 51));
        idMaterialuLabel.setText("ID materialu:");

        idMaterualuTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idMaterualuTextFieldMouseClicked(evt);
            }
        });
        idMaterualuTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idMaterualuTextFieldActionPerformed(evt);
            }
        });

        pocetTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pocetTextFieldActionPerformed(evt);
            }
        });

        cenaLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cenaLabel.setForeground(new java.awt.Color(51, 51, 51));
        cenaLabel.setText("Cena:");

        materialTable.setBackground(new java.awt.Color(0, 204, 102));
        materialTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID pohybu", "ID materialu", "Nazov materialu", "Cena", "Pocet"
            }
        ));
        jScrollPane1.setViewportView(materialTable);

        potvrdPrijemkuButton.setBackground(new java.awt.Color(0, 102, 0));
        potvrdPrijemkuButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        potvrdPrijemkuButton.setText("Potvrdiť");
        potvrdPrijemkuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potvrdPrijemkuButtonActionPerformed(evt);
            }
        });

        stornoButton.setBackground(new java.awt.Color(0, 102, 0));
        stornoButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        stornoButton.setText("Storno");
        stornoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stornoButtonActionPerformed(evt);
            }
        });

        pridajMaterialuButton.setBackground(new java.awt.Color(0, 102, 0));
        pridajMaterialuButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pridajMaterialuButton.setText("Pridaj material");
        pridajMaterialuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridajMaterialuButtonActionPerformed(evt);
            }
        });

        cenaSpoluTextField.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Cena spolu:");

        jSeparator2.setBackground(new java.awt.Color(51, 51, 51));

        jSeparator3.setBackground(new java.awt.Color(51, 51, 51));

        jSeparator4.setBackground(new java.awt.Color(51, 51, 51));

        uzivatelLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uzivatelLabel.setForeground(new java.awt.Color(0, 204, 0));
        uzivatelLabel.setText("Uzivatel");

        vymazPohybMaterialuButton.setBackground(new java.awt.Color(0, 102, 0));
        vymazPohybMaterialuButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        vymazPohybMaterialuButton.setText("Vymaž pohyb");
        vymazPohybMaterialuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vymazPohybMaterialuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(uzivatelLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cenaLabel)
                                    .addComponent(pocetLabel)
                                    .addComponent(idMaterialuLabel))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cenaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                    .addComponent(idMaterualuTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pocetTextField, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pridajMaterialuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vymazPohybMaterialuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(470, 470, 470)
                        .addComponent(idLabel)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(cenaSpoluTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(potvrdPrijemkuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(stornoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(uzivatelLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idMaterualuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idMaterialuLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pocetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pocetLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cenaLabel)
                            .addComponent(cenaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pridajMaterialuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vymazPohybMaterialuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(idLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cenaSpoluTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(potvrdPrijemkuButton)
                .addGap(18, 18, 18)
                .addComponent(stornoButton)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pridajMaterialuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridajMaterialuButtonActionPerformed
       pouzivatel = pouzivatelDao.dajPouzivatela(uzivatelLabel.getText());   
       if(idMaterualuTextField.getText().equals("")){
         JOptionPane.showMessageDialog(null, "Prosim zadajte id materialu");
        return;
        }
        long idMaterialu = Integer.parseInt(idMaterualuTextField.getText());
        Material pridavanyMaterial;
        if(materialDao.dajVsetkyId().contains(idMaterialu)){
        pridavanyMaterial = materialDao.dajMaterialById(idMaterialu); 
        }else{
        JOptionPane.showMessageDialog(null, "Material neexistuje");
        return;
        }
               
        long idSkladuPouzivatela = pouzivatel.getId_sklad();
        long idSkladuMaterialu = pridavanyMaterial.getId_sklad();
        
        if(pocetTextField.getText().equals("")){
         JOptionPane.showMessageDialog(null, "Prosim zadajte pocet");
        return;
        }
        double pocet = Double.parseDouble(pocetTextField.getText());
        long idPrijemky = this.idPrijemky;
          if(cenaTextField.getText().equals("")){
         JOptionPane.showMessageDialog(null, "Prosim zadajte cenu");
        return;
        }
        double cena = Double.parseDouble(cenaTextField.getText());
        if(idSkladuMaterialu==idSkladuPouzivatela){
        PohybMaterialu pohybMaterialu = new PohybMaterialu();        
        pohybMaterialu.setPocet(pocet);
        pohybMaterialu.setPrijemka_id(idPrijemky);
        pohybMaterialu.setCena(cena);
        pohybMaterialu.setVydajka_id(0);
     //   Long idMat
        pohybMaterialu.setId_materialu(idMaterialu);
        pohybMaterialu.setId(pohybMaterialuDao.getLastId());
       // System.out.println(pohybMaterialu.getVydajka_id());
            System.out.println("Ahoj"+pohybMaterialu.toString());
        /*
        materialDao.upravStavMaterial(idMaterialu, pocet, 1);
        double cenaUpravena = upravCenuMaterialu(idMaterialu, cena, pocet);
        materialDao.upravCenuMaterialu(idMaterialu, cenaUpravena);
             */  
        pohybMaterialuDao.pridajPohybMaterialuPrijem(pohybMaterialu);        
        DefaultTableModel model= (DefaultTableModel) materialTable.getModel();        
        model.addRow(new Object[]{pohybMaterialuDao.getLastId(),idMaterialu,materialDao.dajMaterialById(idMaterialu).getNazov(),cena,pocet});
        cenaSpoluTextField.setText(new DecimalFormat("##.##").format(sumaSpolu(model,3,4)).replace(',', '.'));
        }else{
             JOptionPane.showMessageDialog(null, "Material sa nenachadza na sklade");
        }  
    }//GEN-LAST:event_pridajMaterialuButtonActionPerformed

    private void potvrdPrijemkuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potvrdPrijemkuButtonActionPerformed
        Prijemka prijemka = new Prijemka();   
        String timeStamp = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(Calendar.getInstance().getTime());
        prijemka.setId_pouzivatel(pouzivatel.getId());     
        prijemka.setDatum(timeStamp);
        prijemka.setTypPohybu(1L);
        prijemka.setCena(Double.parseDouble(cenaSpoluTextField.getText()));
     //   prijemka.setId(prijemkaDao.getLastId());
        upravCenyMaterialu((DefaultTableModel)materialTable.getModel());
        upravStavMaterialu((DefaultTableModel)materialTable.getModel());
        prijemkaDao.pridajPrijemka(prijemka);     
        
        MainScreen main = new MainScreen();                       
        main.setVisible(true);
        main.uzivatelLable.setText(this.uzivatelLabel.getText());
        this.setVisible(false);
        dispose();
        
    }//GEN-LAST:event_potvrdPrijemkuButtonActionPerformed

    private void stornoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stornoButtonActionPerformed
        prijemkaDao.odstranPrijemku(prijemkaDao.dajPrijemkuById((long)prijemkaDao.getLastId()));
//pohybMaterialuDao.odstranPohybMaterialuByPrijemkaId(pohybMaterialuDao.getLastId());
        MainScreen main = new MainScreen();
        main.setVisible(true);
        main.uzivatelLable.setText(this.uzivatelLabel.getText());
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_stornoButtonActionPerformed

    private void vymazPohybMaterialuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vymazPohybMaterialuButtonActionPerformed
        int row = materialTable.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) materialTable.getModel();
        long id = (Long) model.getValueAt(row, 0); 
        long idMaterialu = (Long) model.getValueAt(row, 1);
        double pocet = (Double) model.getValueAt(row, 4);
       pohybMaterialuDao.odstranPohybMaterialu(pohybMaterialuDao.dajPohybMaterialuById(id));
       
        model.removeRow(row);
        cenaSpoluTextField.setText(new DecimalFormat("##.##").format(sumaSpolu(model,3,4)));
        
    }//GEN-LAST:event_vymazPohybMaterialuButtonActionPerformed

    
    private void idMaterualuTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idMaterualuTextFieldActionPerformed
       
    }//GEN-LAST:event_idMaterualuTextFieldActionPerformed

    private void idMaterualuTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idMaterualuTextFieldMouseClicked
        if(evt.getClickCount()==2){
           VyhliadavanieMaterialScreen VMS = new VyhliadavanieMaterialScreen(this,null,1);
           VMS.uzivatelLabel.setText(this.uzivatelLabel.getText());
           VMS.jLabel3.setText("Prijemka");
           VMS.setVisible(true);
           this.setVisible(false);
         //  VMS.IDLabel2.getText();
     
           //this.
          //dispose();
                 
            
        }
    }//GEN-LAST:event_idMaterualuTextFieldMouseClicked

    private void pocetTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pocetTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pocetTextFieldActionPerformed
 
    
    
    
    
    
    public double sumaSpolu(DefaultTableModel mdl, int columnCena, int columnPocet) {
    double total = 0;  
    for (int i = 0 ; i < mdl.getRowCount() ; i++) {       
         total += (Double) mdl.getValueAt(i, columnCena) * (Double) mdl.getValueAt(i, columnPocet);
    }
    return total;
}
    
    public double upravCenuMaterialu(long idMaterialu, double cena, double pocet){    
    double cenaPoUprave =0;
    double sucetPoctov = 0;
    double sucetSucinov = 0;
    List<PohybMaterialu> pohyby = pohybMaterialuDao.getPohybyByMaterialId(idMaterialu);
    for(PohybMaterialu pohyb : pohyby){
        System.out.println(pohyb.toString());
       sucetSucinov += (pohyb.getCena()*pohyb.getPocet());
       sucetPoctov += pohyb.getPocet();    
    }
    sucetSucinov += cena*pocet;
    sucetPoctov +=pocet;
    
    cenaPoUprave=sucetSucinov/sucetPoctov;
    
    
    return cenaPoUprave;
    
    }
    public void upravCenyMaterialu(DefaultTableModel mdl){ 
      long idMaterialu;
      double pocet;
      double cena;
    for (int i = 0 ; i < mdl.getRowCount() ; i++) {
        idMaterialu =  (Long) mdl.getValueAt(i,1 );
        pocet = (Double) mdl.getValueAt(i, 4);
        cena = (Double) mdl.getValueAt(i, 3);        
        materialDao.upravCenuMaterialu(idMaterialu, upravCenuMaterialu(idMaterialu, cena, pocet));       
    }  
    }
    
    public void upravStavMaterialu(DefaultTableModel mdl){
      long idMaterialu;
     double pocet;         
     for (int i = 0 ; i < mdl.getRowCount() ; i++) {
        idMaterialu =  (Long) mdl.getValueAt(i,1);
        pocet = (Double) mdl.getValueAt(i, 4);
           materialDao.upravStavMaterial(idMaterialu, pocet, 1);    
          
    } 
    
  
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VytvorPrijemkuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VytvorPrijemkuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VytvorPrijemkuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VytvorPrijemkuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VytvorPrijemkuScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cenaLabel;
    private javax.swing.JTextField cenaSpoluTextField;
    private javax.swing.JTextField cenaTextField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel idMaterialuLabel;
    public javax.swing.JTextField idMaterualuTextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable materialTable;
    private javax.swing.JLabel pocetLabel;
    private javax.swing.JTextField pocetTextField;
    private javax.swing.JButton potvrdPrijemkuButton;
    private javax.swing.JButton pridajMaterialuButton;
    private javax.swing.JButton stornoButton;
    public javax.swing.JLabel uzivatelLabel;
    private javax.swing.JButton vymazPohybMaterialuButton;
    // End of variables declaration//GEN-END:variables

  
}
