/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ics.upjs.sk.paz1c.skladnik.gui;

import Factory.ObjectFactory;
import dao.MaterialDao;
import dao.PohybMaterialuDao;
import dao.PrijemkaDao;
import dao.VydajkaDao;
import ics.upjs.sk.paz1c.skladnik.entity.PohybMaterialu;
import ics.upjs.sk.paz1c.skladnik.entity.Prijemka;
import ics.upjs.sk.paz1c.skladnik.entity.Vydajka;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcel
 */
public class ZobrazPohybScreen extends javax.swing.JFrame {
public PrijemkaDao prijemkaDao;
public VydajkaDao vydajkaDao;
 public MaterialDao materialDao;
 public PohybMaterialuDao pohybMaterialuDao;


    
 
 
 
 
    /**
     * Creates new form ZobrazPrijemkuScreen
     */
    public ZobrazPohybScreen() {
        initComponents();
        pohybMaterialuDao = ObjectFactory.INSTANCE.getPohybMaterialuDao();
        prijemkaDao = ObjectFactory.INSTANCE.getPrijemkadDao();
        materialDao = ObjectFactory.INSTANCE.getMaterialDao();   
        vydajkaDao= ObjectFactory.INSTANCE.getVydajkaDao();

       }
    
    
    
    
    public void naplnTabulkuPrijmi(){
      
        DefaultTableModel model = (DefaultTableModel)zobrazPohybyTable.getModel();       
        typPohybuTextField.setText("1");
        List<PohybMaterialu> pohyby = pohybMaterialuDao.getAllPohybyByPrijemkaId(Long.parseLong(idScreenTextField.getText()));        
        for(PohybMaterialu pohybMaterialu : pohyby){
       model.addRow(new Object[]{materialDao.dajMaterialById(pohybMaterialu.getId_materialu()).getId(), materialDao.dajMaterialById(pohybMaterialu.getId_materialu()).getNazov(),pohybMaterialu.getCena(),pohybMaterialu.getPocet()});
    }
    }
    
     public void naplnTabulkuVydaje(){
      
        DefaultTableModel model = (DefaultTableModel)zobrazPohybyTable.getModel();      
        typPohybuTextField.setText("2");
        List<PohybMaterialu> pohyby = pohybMaterialuDao.getAllPohybyByVydajkaId(Long.parseLong(idScreenTextField.getText()));        
        for(PohybMaterialu pohybMaterialu : pohyby){
       model.addRow(new Object[]{materialDao.dajMaterialById(pohybMaterialu.getId_materialu()).getId(), materialDao.dajMaterialById(pohybMaterialu.getId_materialu()).getNazov(),pohybMaterialu.getCena(),pohybMaterialu.getPocet()});
    }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        zobrazPohybyTable = new javax.swing.JTable();
        idScreenTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        typPohybuTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        spatButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        zobrazPohybyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id materialu", "Nazov materialu", "pocet", "cena"
            }
        ));
        jScrollPane1.setViewportView(zobrazPohybyTable);

        idScreenTextField.setEditable(false);
        idScreenTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ID:");

        typPohybuTextField.setEditable(false);
        typPohybuTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Typ pohybu:");

        spatButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spatButton.setText("Späť");
        spatButton.setToolTipText("");
        spatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spatButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(20, 20, 20)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(typPohybuTextField)
                    .addComponent(idScreenTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(spatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idScreenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(typPohybuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(spatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spatButtonActionPerformed
       MainScreen main = new MainScreen();
       main.setVisible(true);
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_spatButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZobrazPohybScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZobrazPohybScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZobrazPohybScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZobrazPohybScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZobrazPohybScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField idScreenTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton spatButton;
    private javax.swing.JTextField typPohybuTextField;
    private javax.swing.JTable zobrazPohybyTable;
    // End of variables declaration//GEN-END:variables
}
