/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ics.upjs.sk.paz1c.skladnik.gui;

import Factory.ObjectFactory;
import dao.MaterialDao;
import dao.PohybMaterialuDao;
import dao.SkladDao;
import ics.upjs.sk.paz1c.skladnik.entity.Material;
import ics.upjs.sk.paz1c.skladnik.entity.PohybMaterialu;
import java.awt.Color;
import java.awt.Component;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Marcel
 */
public class zobrazKartuMaterialu extends javax.swing.JFrame {
    
    PohybMaterialuDao pohybMaterialuDao = ObjectFactory.INSTANCE.getPohybMaterialuDao();
    MaterialDao materialDao = ObjectFactory.INSTANCE.getMaterialDao();
    SkladDao skladDao = ObjectFactory.INSTANCE.getSkladDao();
    PohybCellRenderer pohybCellRenderer = new PohybCellRenderer();

    /**
     * Creates new form zobrazKartuMaterialu
     */
    public zobrazKartuMaterialu() {
        initComponents();
        
        
    }
    
    
    
   
    
    
    
    
    
    public void naplnPohybyTable(){
    Material material = materialDao.dajMaterialById(Long.parseLong(idMaterialuTextField.getText()));
    stavTextField.setText(material.getStav()+"");
    cenaTextField.setText(new DecimalFormat("##.##").format(material.getCena()).replace(',','.'));
    SkladTextField.setText(skladDao.dajSklad(material.getId_sklad()).getNazov());    
    DefaultTableModel model = new DefaultTableModel();  
    model = (DefaultTableModel) pohybyMaterialuTable.getModel();   
    List<PohybMaterialu> pohyby = pohybMaterialuDao.getPohybyByMaterialId(Long.parseLong(idMaterialuTextField.getText()));    
        for(PohybMaterialu pohyb : pohyby){  
            
            if(pohyb.getPrijemka_id()!=0){
        model.addRow(new Object[]{pohyb.getId(),pohyb.getPocet(),new DecimalFormat("##.##").format(pohyb.getCena()).replace(',','.'),pohyb.getPrijemka_id(),1});
                    }
            if(pohyb.getVydajka_id()!=0){
                model.addRow(new Object[]{pohyb.getId(),pohyb.getPocet(),new DecimalFormat("##.##").format(pohyb.getCena()).replace(',','.'),pohyb.getVydajka_id(),2});
                 
            }       
          
             pohybyMaterialuTable.setDefaultRenderer(Object.class, pohybCellRenderer);
            
             
      
        
    
        }
    }
    
    
    class PohybCellRenderer extends DefaultTableCellRenderer {
   public Component getTableCellRendererComponent(
            JTable table, Object value, boolean isSelected,
            boolean hasFocus, int row, int column)
   {
      DefaultTableModel model = (DefaultTableModel) table.getModel();
     Integer typPohybu = (Integer) model.getValueAt(row,4);
       System.out.println(typPohybu);
  
      if (typPohybu == 1) {
         setBackground(new Color(92,255,158));
      }
      else {
         setBackground(new Color(255,114,114));
      }
  
      return super.getTableCellRendererComponent(table, value, isSelected,
                                                 hasFocus, row, column);
   }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pohybyMaterialuTable = new javax.swing.JTable();
        stornoButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        idMaterialuTextField = new javax.swing.JTextField();
        stavTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cenaTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SkladTextField = new javax.swing.JTextField();
        uzivatelLabel = new javax.swing.JLabel();
        zobrazPohybyPrijemkyButton = new javax.swing.JButton();
        zobrazVydajkyPohybyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pohybyMaterialuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "pocet", "cena", "idP", "typ pohybu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pohybyMaterialuTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pohybyMaterialuTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(pohybyMaterialuTable);

        stornoButton.setText("Storno");
        stornoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stornoButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ID materialu");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Stav");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Cena");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Skladu");

        uzivatelLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uzivatelLabel.setForeground(new java.awt.Color(0, 204, 0));
        uzivatelLabel.setText("uzivatel");

        zobrazPohybyPrijemkyButton.setText("Zobraz prijemky");
        zobrazPohybyPrijemkyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zobrazPohybyPrijemkyButtonActionPerformed(evt);
            }
        });

        zobrazVydajkyPohybyButton.setText("Zobraz vydajky");
        zobrazVydajkyPohybyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zobrazVydajkyPohybyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stornoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uzivatelLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cenaTextField)
                                    .addComponent(SkladTextField)
                                    .addComponent(stavTextField)
                                    .addComponent(idMaterialuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(zobrazVydajkyPohybyButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(zobrazPohybyPrijemkyButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(uzivatelLabel)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(idMaterialuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stavTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cenaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(SkladTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addComponent(zobrazPohybyPrijemkyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(zobrazVydajkyPohybyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(stornoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stornoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stornoButtonActionPerformed
        MainScreen main = new MainScreen();
        main.setVisible(true);
        main.uzivatelLable.setText(this.uzivatelLabel.getText());
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_stornoButtonActionPerformed

    private void zobrazVydajkyPohybyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zobrazVydajkyPohybyButtonActionPerformed
        DefaultTableModel model = new DefaultTableModel();  
        model = (DefaultTableModel) pohybyMaterialuTable.getModel();   
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        List<PohybMaterialu> pohyby = pohybMaterialuDao.getAllPohybyByMaterialIdVydajky(Long.parseLong(idMaterialuTextField.getText()));    
        for(PohybMaterialu pohyb : pohyby){ 
            model.addRow(new Object[]{pohyb.getId(),pohyb.getPocet(),new DecimalFormat("##.##").format(pohyb.getCena()).replace(',','.'),pohyb.getPrijemka_id(),2});
        
        }
    }//GEN-LAST:event_zobrazVydajkyPohybyButtonActionPerformed

    private void zobrazPohybyPrijemkyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zobrazPohybyPrijemkyButtonActionPerformed
          DefaultTableModel model = new DefaultTableModel();  
        model = (DefaultTableModel) pohybyMaterialuTable.getModel();   
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        List<PohybMaterialu> pohyby = pohybMaterialuDao.getAllPohybyByMaterialIdPrijemky(Long.parseLong(idMaterialuTextField.getText()));    
        for(PohybMaterialu pohyb : pohyby){ 
            model.addRow(new Object[]{pohyb.getId(),pohyb.getPocet(),new DecimalFormat("##.##").format(pohyb.getCena()).replace(',','.'),pohyb.getPrijemka_id(),1});
        
        }
    }//GEN-LAST:event_zobrazPohybyPrijemkyButtonActionPerformed

    private void pohybyMaterialuTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pohybyMaterialuTableMouseClicked
             if(evt.getClickCount()==2){
       int row = pohybyMaterialuTable.getSelectedRow();      
       TableModel model = pohybyMaterialuTable.getModel();
       String id = model.getValueAt(row, 0).toString();  
            
      
       
                      
       
    
       String typPohybu = model.getValueAt(row, 4).toString(); 
       if(typPohybu.equals("1")){
       ZobrazPohybScreen zobrazPrijemkuScreen = new ZobrazPohybScreen();
       zobrazPrijemkuScreen.uzivatelLabel.setText(this.uzivatelLabel.getText());
       zobrazPrijemkuScreen.idScreenTextField.setText((Long) model.getValueAt(row, 3)+"");
       zobrazPrijemkuScreen.naplnTabulkuPrijmi();
       zobrazPrijemkuScreen.setVisible(true);
       this.setVisible(false);
      
       }

       
        if(typPohybu.equals("2")){
       ZobrazPohybScreen zobrazVydajkuScreen = new ZobrazPohybScreen();
       zobrazVydajkuScreen.uzivatelLabel.setText(this.uzivatelLabel.getText());
       zobrazVydajkuScreen.idScreenTextField.setText((Long) model.getValueAt(row, 3)+"");
       zobrazVydajkuScreen.naplnTabulkuVydaje();
       zobrazVydajkuScreen.setVisible(true);
       this.setVisible(false);
     
       }
             }
    }//GEN-LAST:event_pohybyMaterialuTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(zobrazKartuMaterialu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(zobrazKartuMaterialu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(zobrazKartuMaterialu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(zobrazKartuMaterialu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new zobrazKartuMaterialu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SkladTextField;
    private javax.swing.JTextField cenaTextField;
    public javax.swing.JTextField idMaterialuTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable pohybyMaterialuTable;
    private javax.swing.JTextField stavTextField;
    private javax.swing.JButton stornoButton;
    public javax.swing.JLabel uzivatelLabel;
    private javax.swing.JButton zobrazPohybyPrijemkyButton;
    private javax.swing.JButton zobrazVydajkyPohybyButton;
    // End of variables declaration//GEN-END:variables
}
